# Generated by Django 3.1.2 on 2020-11-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201123_1555'),
        ('news', '0002_auto_20201123_1449'),
    ]

    operations = [
    ]
